import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const dataDir = path.join(__dirname, 'characters', 'data');
const outputJsPath = path.join(__dirname, 'resources', 'characters-data.js');
const outputJsonPath = path.join(__dirname, 'resources', 'characters.json');

function stripComments(jsonString) {
    // Regex to match strings or comments
    // Group 1: Comments (// or /* */)
    const regex = /\\"|"(?:\\"|[^"])*"|(\/\/.*|\/\*[\s\S]*?\*\/)/g;
    return jsonString.replace(regex, (match, comment) => {
        if (comment) {
            return ''; // Remove comment
        }
        return match; // Keep string
    });
}

function updateCharactersData() {
    console.log('Updating characters data...');
    
    if (!fs.existsSync(dataDir)) {
        console.error(`Data directory not found: ${dataDir}`);
        return;
    }

    const files = fs.readdirSync(dataDir).filter(file => file.endsWith('.json'));
    const charactersData = {};

    files.forEach(file => {
        const filePath = path.join(dataDir, file);
        try {
            const content = fs.readFileSync(filePath, 'utf8');
            const data = JSON.parse(stripComments(content));
            if (data.id) {
                charactersData[data.id] = data;
            } else {
                console.warn(`Skipping ${file}: Missing 'id' field.`);
            }
        } catch (err) {
            console.error(`Error reading ${file}:`, err.message);
        }
    });

    // Write JSON file
    fs.writeFileSync(outputJsonPath, JSON.stringify(charactersData, null, 4), 'utf8');
    console.log(`Generated ${outputJsonPath}`);

    // Write JS file for frontend inclusion
    const jsContent = `// Auto-generated by update_script.js\nwindow.charactersData = ${JSON.stringify(charactersData, null, 4)};\n`;
    fs.writeFileSync(outputJsPath, jsContent, 'utf8');
    console.log(`Generated ${outputJsPath}`);
}

// Initial update
updateCharactersData();

// Watch mode
if (process.argv.includes('--watch')) {
    console.log(`Watching for changes in ${dataDir}...`);
    fs.watch(dataDir, (eventType, filename) => {
        if (filename && filename.endsWith('.json')) {
            console.log(`Detected change in ${filename} (${eventType})`);
            // Debounce could be added here, but for now simple call is fine
            updateCharactersData();
        }
    });
}
